package com.tiptop.dao;

import java.util.List;

import com.tiptop.model.Websites;

public interface WebsitesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbggenerated
     */
    int insert(Websites websites);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbggenerated
     */
    int insertSelective(Websites websites);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbggenerated
     */
    Websites selectByPrimaryKey(Integer websites);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbggenerated
     */
    
    List<Websites> findAllWebsites();
    /**
     * 
     * @return allWebsitesInformation
     */
    
    int updateByPrimaryKeySelective(Websites websites);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table websites
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Websites websites);
}